version: '3.7'
services:
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/lib/node_exporter/textfile_collector:/var/lib/node_exporter/textfile_collector:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|run|boot|rootfs/var/lib/|var|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      - --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
    network_mode: host
    restart: always
    privileged: true

  # smartctl-exporter:
  #   image: prometheuscommunity/smartctl-exporter
  #   privileged: true
  #   user: root
  #   ports:
  #     - "9633:9633"
