version: '3.7'


services:
  process-exporter:
    image: ncabatoff/process-exporter
    volumes: 
      - /proc:/host/proc
      - ./filename.yml:/config/filename.yml
    command: 
      - --procfs
      - /host/proc
      - -config.path 
      - /config/filename.yml
      
    network_mode: host

    
    restart: always
    privileged: true
